import fs from 'fs';
import { generateRefrainData, RawSongData } from './lyricsExtractor.js';
import { MASTER_DATA } from '../data/fullMasterData.js';

async function fetchLyrics(artist: string, title: string): Promise<string | null> {
  try {
    // Using lrclib.net API which is generally more accurate
    const url = `https://lrclib.net/api/get?artist_name=${encodeURIComponent(artist)}&track_name=${encodeURIComponent(title)}`;
    const response = await fetch(url);
    if (!response.ok) {
      return null;
    }
    const data = await response.json();
    return data.plainLyrics || data.syncedLyrics || null;
  } catch (error) {
    console.error(`Error fetching lyrics for ${artist} - ${title}:`, error);
    return null;
  }
}

async function run() {
  // Filter songs with weight >= 75
  const targetSongs = MASTER_DATA.filter(song => song.weight && song.weight >= 75);
  
  console.log(`Found ${targetSongs.length} songs with weight >= 75.`);
  console.log(`Starting to fetch lyrics...`);
  
  const rawData: RawSongData[] = [];
  let successCount = 0;
  let failCount = 0;

  for (const song of targetSongs) {
    console.log(`Fetching: ${song.artist} - ${song.title} (Weight: ${song.weight})...`);
    const lyrics = await fetchLyrics(song.artist, song.title);
    
    if (lyrics) {
      rawData.push({
        id: song.id,
        title: song.title,
        artist: song.artist,
        year: song.year,
        lyrics: lyrics,
        placing: song.placing
      });
      console.log(`✅ Success`);
      successCount++;
    } else {
      console.log(`❌ Not found`);
      failCount++;
    }
    
    // Small delay to avoid rate limiting
    await new Promise(resolve => setTimeout(resolve, 200));
  }

  console.log(`\nSuccessfully fetched lyrics for ${successCount} songs. Failed for ${failCount} songs.`);
  console.log('Extracting refrains...');

  const extracted = generateRefrainData(rawData);

  const outputContent = `import { LyricSnippet } from './types.ts';

// This file was auto-generated by fetching from lrclib.net API
// and extracting snippets using the lyricsExtractor utility.
export const REFRAIN_DATA_V2: LyricSnippet[] = ${JSON.stringify(extracted, null, 2)};
`;

  fs.writeFileSync('./data/refrainData-v2.ts', outputContent);
  console.log(`Extraction complete. Wrote ${extracted.length} snippets to data/refrainData-v2.ts`);
}

run();
