/**
 * Eurovision Categories for EuroLinks game.
 * Generated by AI based on Eurovision history.
 */

export interface LinkSubCategory {
  name: string;
  items: string[];
}

export interface LinkMainCategory {
  main: string;
  subs: LinkSubCategory[];
}

export const LINKS_CATEGORIES: LinkMainCategory[] = [
  {
    main: "Countries",
    subs: [
      { name: "Nordic Countries", items: ["SWEDEN", "NORWAY", "FINLAND", "DENMARK", "ICELAND"] },
      { name: "Big Five", items: ["FRANCE", "GERMANY", "ITALY", "SPAIN", "UNITED KINGDOM"] },
      { name: "Baltic States", items: ["ESTONIA", "LATVIA", "LITHUANIA"] },
      { name: "Yugoslav Successor States", items: ["SERBIA", "CROATIA", "SLOVENIA", "MONTENEGRO", "NORTH MACEDONIA", "BOSNIA AND HERZEGOVINA"] }
    ]
  },
  {
    main: "Artists",
    subs: [
      { name: "Multiple Winners", items: ["LOREEN", "JOHNNY LOGAN"] },
      { name: "Artists who also hosted", items: ["MANS ZELMERLOW", "CONCHITA WURST", "EDSYLIA ROMBLEY", "PETRA MEDE"] },
      { name: "Artists with one-word names", items: ["LOREEN", "LENA", "RUSLANA", "SERTAB", "MARIJA"] },
      { name: "Artists who represented multiple countries", items: ["ANNE-MARIE DAVID", "VICKY LEANDROS", "ROMINA POWER", "AL BANO"] }
    ]
  }
];
