import fs from 'fs';
import path from 'path';
import { GoogleGenAI, Type } from "@google/genai";
import { MASTER_DATA } from '../data/fullMasterData.ts';

/**
 * This script uses the Gemini API to brainstorm Eurovision-themed categories for the EuroLinks game.
 * It outputs a structured TypeScript file: data/linksCategories.ts
 * 
 * Usage:
 *   GEMINI_API_KEY=your_key npx tsx utils/generateLinksCategories.ts
 */

const apiKey = process.env.GEMINI_API_KEY;

if (!apiKey) {
  console.error("Error: GEMINI_API_KEY environment variable is not set.");
  console.error("Usage: GEMINI_API_KEY=your_key npx tsx utils/generateLinksCategories.ts");
  process.exit(1);
}

const ai = new GoogleGenAI({ apiKey });

// Helper to get unique values for brainstorming context
const uniqueCountries = Array.from(new Set(MASTER_DATA.map(m => m.country))).sort();
const uniqueYears = Array.from(new Set(MASTER_DATA.map(m => m.year))).sort();
const sampleArtists = MASTER_DATA.slice(0, 100).map(m => m.artist);
const sampleTitles = MASTER_DATA.slice(0, 100).map(m => m.title);

const prompt = `
You are a Eurovision expert and game designer. I am building a "Connections" style game called EuroLinks.
I need a structured dataset of Eurovision facts.

The structure should be:
Main Category (e.g., "Countries", "Artists", "Years", "Song Titles", "Lyrics", "Cities", "Instruments", "Costumes", "Props")
  - Sub Category (e.g., "Countries that have won more than twice", "Artists who returned as a host", "Years with a tie for 1st place")
    - Items (At least 4 items per sub-category. Items must be strings that fit the Main Category type).

Guidelines:
1. Facts MUST be Eurovision-related or common knowledge relevant to the participants (e.g., "Countries ending in -land" is fine, but "Countries with a GDP of X" is not).
2. Prefer interesting, clever, or challenging trivia.
3. Each sub-category must have at least 4 items.
4. Aim for at least 15 Main Categories, and as many Sub-Categories as possible (aim for 10-20 per main category).
5. Ensure items are accurate to Eurovision history (1956-2025).

Context for you:
- Countries involved: ${uniqueCountries.join(", ")}
- Years: ${uniqueYears[0]} to ${uniqueYears[uniqueYears.length - 1]}
- Examples of Artists: ${sampleArtists.slice(0, 20).join(", ")}...
- Examples of Titles: ${sampleTitles.slice(0, 20).join(", ")}...

Please return the data in a JSON format that matches this schema:
{
  "categories": [
    {
      "main": "Main Category Name",
      "subs": [
        { "name": "Sub Category Name", "items": ["item1", "item2", "item3", "item4", ...] }
      ]
    }
  ]
}
`;

async function generate() {
  console.log("Generating Eurovision categories with Gemini...");
  
  try {
    const response = await ai.models.generateContent({
      model: "gemini-3.1-pro-preview",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            categories: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  main: { type: Type.STRING },
                  subs: {
                    type: Type.ARRAY,
                    items: {
                      type: Type.OBJECT,
                      properties: {
                        name: { type: Type.STRING },
                        items: {
                          type: Type.ARRAY,
                          items: { type: Type.STRING }
                        }
                      },
                      required: ["name", "items"]
                    }
                  }
                },
                required: ["main", "subs"]
              }
            }
          },
          required: ["categories"]
        }
      }
    });

    const result = JSON.parse(response.text);
    
    const outputPath = path.resolve("./data/linksCategories.ts");
    
    const fileContent = `/**
 * Eurovision Categories for EuroLinks game.
 * Generated by AI based on Eurovision history.
 */

export interface LinkSubCategory {
  name: string;
  items: string[];
}

export interface LinkMainCategory {
  main: string;
  subs: LinkSubCategory[];
}

export const LINKS_CATEGORIES: LinkMainCategory[] = ${JSON.stringify(result.categories, null, 2)};
`;

    fs.writeFileSync(outputPath, fileContent);
    console.log(`Successfully generated categories and saved to ${outputPath}`);
    console.log(`Total Main Categories: ${result.categories.length}`);
    
    let totalSubs = 0;
    result.categories.forEach((c: any) => totalSubs += c.subs.length);
    console.log(`Total Sub-Categories: ${totalSubs}`);

  } catch (error) {
    console.error("Error generating categories:", error);
    process.exit(1);
  }
}

generate();
